# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96aaa3b38d8d0895e6b65d44febdfb29062e467908540d7fa7db2c14e499f9d1e243fba5e6572fd27338218d3e08df12cca8dd7cee2474d935ec959f990c367a

test:
  secret_key_base: e60ce62aa90a1d3a26a764fd12d8b9f7600854db82f181f1052459412b0d54e5164c255d8a24118d6a938102dda1382aa61aa6dc9eedfa560dca958ca25a7c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
